version: "3"

services:
    adminer:
      image: adminer
      restart: always
      ports:
       - 80:8080
      networks: 
       - bot

    bot:
        build: ./PythonBot
        depends_on:
            - db
        networks: 
            - bot

    db:
        image: postgres:alpine
        restart: on-failure
        environment:
            - POSTGRES_DB=server
            - POSTGRES_ROOT_PASSWORD=root
            - POSTGRES_USER=vlad
            - POSTGRES_PASSWORD=vlad
        ports:
            - "5432:5432"
        networks: 
            - bot


networks: 
    bot: